# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'submissioncounter' do
  pod 'AppCenter/Crashes', '~> 1.13.2'
  pod 'AppCenter/Analytics', '~> 1.13.2'
  pod 'AppCenterReactNativeShared', '~> 1.12.2'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for submissioncounter

  platform :ios, '9.0'
  pod 'react-native-haptic-feedback', :path => '../node_modules/react-native-haptic-feedback'

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  target 'submissioncounterTests' do
    inherit! :search_paths
    # Pods for testing
  end
end