platform :ios, '9.0'

# The target name is most likely the name of your project.
target 'submissioncounter' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'AppCenter/Crashes', '~> 1.13.2'
  pod 'AppCenter/Analytics', '~> 1.13.2'
  pod 'AppCenterReactNativeShared', '~> 1.12.2'
  # pod 'CodePush', :path => '../node_modules/react-native-code-push'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    targets_to_ignore = %w(React yoga)

    if targets_to_ignore.include? target.name
      target.remove_from_project
    end

    # if target.name == 'react-native-config'
    #   phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
    #   phase.shell_script = "cd ../../"\
    #                        " && RNC_ROOT=./node_modules/react-native-config/"\
    #                        " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
    #                        " && export BUILD_DIR=$RNC_ROOT/ios/ReactNativeConfig"\
    #                        " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"
    #
    #   target.build_phases << phase
    #   target.build_phases.move(phase, 0)
    # end
  end
end
